[manager]
prepend_keymap = [
	{ on = "1", run = 'quit', desc = "Exit the process" },
  { on = "q", run = 'my-fev-command1', desc = "Just for test!" },
# { on   = "!",    run  = 'shell "$SHELL" --block --confirm', desc = "Open shell here"},
]
